server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

---

spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mybatis:
    mapper-locations:
      - classpath:mapper/**.xml
    configuration:
      map-underscore-to-camel-case: true
server:
  port: 8080

#---
#
#spring:
#  profiles: mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/board
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root1234
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#  mybatis:
#    mapper-locations:
#      - classpath:mapper/**.xml
#    configuration:
#      map-underscore-to-camel-case: true

---

spring:
  profiles: admin
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mybatis:
    mapper-locations:
      - classpath:mapper/**.xml
    configuration:
      map-underscore-to-camel-case: true
server:
  port: 9000